PHP Documentor
keopiwauyu/ExamplePlugin pull request #3
Opened 2022-07-20 18:01 UTC by Endermanbugzjfc

2022-07-20 19:01 UTC, Endermanbugzjfc commented
# [Preview (not permanent)](https://endermanbugzjfc.github.io/ExamplePlugin/docs)

2022-07-26 17:57 UTC, keopiwauyu requested changes
setup php need time nad pcoektmei n have many file

2022-07-26 17:57 UTC, keopiwauyu commented on .github/workflows/poggit.yml
> +        docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 -t ./docs
```suggestion
    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Define link param under pull request event context
      if: contains(github.event_name, 'pull_request')
      id: link
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "::set-output name=link::#${{ github.event.pull-request-number }}"
    - name: Run phpdoc
      run: |
        docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 -t ./docs
```

2022-07-26 17:58 UTC, merged

2022-07-26 17:58 UTC, keopiwauyu commented
stop put bad word in commit or i ban you